timeTracker/timeLogger/urls.py
from django.conf.urls import patterns, url
from timeLogger import views

urlpatterns =  patterns('',
        url(r'^$', views.showTodaysLogs, name='logs'),
        url(r'all/$', views.showAllLogs, name='showAllLogs'),
        url(r'add/(\d+)/$', views.addLog, name='addLog'),
        url(r'last7/$', views.showLast7Logs, name='logsLast7'),
        url(r'activities/$', views.showActivities, name='showActivities'),
        url(r'activities/(\d+)/remove$', views.delActivity, name='delActivity'),
        url(r'(\d+)/remove$', views.delLog, name='delLog'),
        url(r'(\d+)/edit$', views.editLog, name='editLog'),

)

timeTracker/timeTracker/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
      url(r'^$', 'timeTracker.views.home', name='home'),
    # url(r'^timeTracker/', include('timeTracker.foo.urls')),
      url(r'^logs/', include('timeLogger.urls')),
         (r'^accounts/', include('userena.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
      url(r'^admin/', include(admin.site.urls)),
)

timeTracker/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from userena.models import UserenaBaseProfile

class MyProfile(UserenaBaseProfile):
    user = models.OneToOneField(User,
                                unique=True,
                                verbose_name=_('user'),
                                related_name='my_profile')
    favourite_snack = models.CharField(_('favourite snack'),
                                       max_length=5)

timeTracker/timeLogger/models.py
from django.db import models
from accounts.models import MyProfile
# Create your models here.

class dailySummary(models.Model):
    account = models.ForeignKey(MyProfile)
    ratings = (
            ('1','1'),
            ('2','2'),
            ('3','3'),
            ('4','4'),
            ('5','5'),
            )
    date = models.DateField()
    rating = models.CharField(max_length=1, choices=ratings, blank=True)

    def __unicode__(self):
        return u'%s %s %s' % (self.account.user, self.date, self.rating)
    
class Activity(models.Model):
    name = models.CharField(max_length=20)
    account = models.ForeignKey(MyProfile)

    def __unicode__(self):
        return self.name

class logActivity(models.Model):
    name = models.ForeignKey('Activity')
    date = models.DateField()
    time = models.IntegerField()
    notes = models.TextField(blank=True)
    account = models.ForeignKey(MyProfile)
    
    def __unicode__(self):
        return u'%s %s' % (self.name, self.notes)

timeTracker/timeLogger/forms.py
from django.forms import ModelForm
from timeLogger.views import logActivity, Activity, dailySummary

class dailySummaryForm(ModelForm):
    class Meta:
        model = dailySummary

class LogActivityForm(ModelForm):
    class Meta:
        model = logActivity
        exclude = ('account','date','name',)

class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        exclude = ('account',)

timeTracker/accounts/views.py
# Create your views here.

timeTracker/timeLogger/views.py
# Create your views here.
from django.db.models import Sum
from timeLogger.models import logActivity, Activity, dailySummary
from timeLogger.forms import LogActivityForm, ActivityForm, dailySummaryForm
from accounts.models import MyProfile
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import datetime

@login_required(login_url='/accounts/signin')
def addLog(request, actId):
    accountId = MyProfile.objects.get(user_id=request.user.id)
    activityName = Activity.objects.get(account_id=accountId.id,id=actId)
    if activityName:
        log = logActivity(account_id=accountId.id,name_id=activityName.id)
        f = logActivity.objects.create(date=datetime.date.today(),time= 0,account_id=accountId.id,name_id=activityName.id)
        f.save()
        return redirect('editLog',f.id)
    else:
        return redirect('logs')

@login_required(login_url='/accounts/signin')
def showTodaysLogs(request):
    accountId = MyProfile.objects.get(user_id=request.user.id)
    activities = Activity.objects.filter(account_id=accountId.id)
    print activities
    logs = logActivity.objects.filter(date=datetime.date.today(),account_id=accountId.id)
    totalTime = logActivity.objects.filter(date=datetime.date.today(),account_id=accountId.id).aggregate(Sum('time'))
    totalTime = totalTime['time__sum']
    return render(request,'log.html',locals())

@login_required(login_url='/accounts/signin')
def showLast7Logs(request):
    accountId = MyProfile.objects.get(user_id=request.user.id)
    dateRange = datetime.date.today()-datetime.timedelta(days=7)
    logs = logActivity.objects.filter(date__gte=dateRange,account_id=accountId.id).order_by('-date')
    totalTime = logActivity.objects.filter(date__gte=dateRange,account_id=accountId.id).aggregate(Sum('time'))
    totalTime = totalTime['time__sum']
    return render(request,'detailedLog.html',locals())

@login_required(login_url='/accounts/signin')
def showAllLogs(request):
    accountId = MyProfile.objects.get(user_id=request.user.id)
    logs = logActivity.objects.filter(account_id=accountId.id)
    totalTime = logActivity.objects.filter(account_id=accountId.id).aggregate(Sum('time'))
    totalTime = totalTime['time__sum']
    return render(request,'allLogs.html',locals())

@login_required(login_url='/accounts/signin')
def showActivities(request):
    accountId = MyProfile.objects.get(user_id=request.user.id)
    if request.method == 'GET':
        activities = Activity.objects.filter(account_id=accountId.id)
        context = {'activities':activities}
        form = ActivityForm()
        return render(request,'activities.html',locals())
    elif request.method == 'POST':
        accountId = MyProfile.objects.get(user_id=request.user.id)
        form = Activity(account_id=accountId.id)
        form = ActivityForm(request.POST, instance=form)
        if form.is_valid():
            form.save()
            return redirect('showActivities')
        else:
            activities = Activity.objects.filter(account_id=accountId.id)
            return render(request,'activities.html',locals())

@login_required(login_url='/accounts/signin')
def editLog(request, logId):
    accountId = MyProfile.objects.get(user_id=request.user.id)
    logs = logActivity.objects.get(account_id=accountId.id, id=logId)
    if request.method == 'GET':
        form = LogActivityForm(instance=logs)
        return render(request,'form.html',locals())
    elif request.method == 'POST':
        postValues = request.POST.copy()
        try:
            b = postValues['time'].split(':')
            time = int(b[0]) * 3600 + int(b[1]) * 60 + int(b[2])
            postValues['time'] = time
        except:
            pass
        form = LogActivityForm(postValues, instance=logs)
        if form.is_valid():
            form.save()
            if dailySummary.objects.filter(account_id=accountId.id,date=datetime.date.today()).exists():
                pass
            else:
                data = {'date' : datetime.date.today(),
                        'account' : accountId.id,
                        'rating' : ''}
                f = dailySummaryForm(data)
                if f.is_valid():
                    f.save()
                else:
                    pass
            return redirect('logs')
        else:
            form.errors['time'] = "Format must be in HH:MM:SS"
            return render(request,'form.html',locals())

@login_required(login_url='/accounts/signin')
def delLog(request, logId):
    accountId = MyProfile.objects.get(user_id=request.user.id)
    logActivity.objects.get(account_id=accountId.id,id=logId).delete()
    return redirect('logs')

@login_required(login_url='/accounts/signin')
def delActivity(request, logId):
    accountId = MyProfile.objects.get(user_id=request.user.id)
    Activity.objects.get(account_id=accountId.id,id=logId).delete()
    return redirect('showActivities')

timeTracker/timeTracker/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html',locals())

timeTracker/timeLogger/templates/activities.html
{% extends "base.html" %}

{% block nav %}
    <li><a href="{% url 'logs' %}">Activity Log</a></li>
    <li class="active"><a href="{% url 'showActivities' %}">Activities</a></li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h1>Activities</h1>
        <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
            {% for i in activities %}
                <td>{{ i.name }}</td>
                <td><a href="{% url 'delActivity' i.id %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></button></a></li>
            </tr>
                        {% endfor %}
        </tbody>
    </table>
    </div>
    <div class="col-md-6">
        <h1>Add Activity</h1>
            <form action="" method="post">{% csrf_token %}
                <table class="table table-condensed">
                    {% for field in form %}
                <tr>
                    <th>
                        {{ field.label_tag }}
                        {{ field.errors }}
                    </th>
                    <td> {{ field }} 
                    </td>
                </tr>
                {% endfor %}
                </table>
            </form>
                <button type="button" onclick="document.forms[0].submit();return false;" class="btn btn-primary">Add Activity</button>
     </div>
</div>
{% endblock %}
{% block js %}
$(document).ready(function(){ 
$("input").addClass("form-control");
})
{% endblock %}

timeTracker/timeLogger/templates/allLogs.html
{% extends "base.html" %}
{% block nav %}
    <li><a href="{% url 'logs' %}">Activity Log</a></li>
    <li><a href="{% url 'showActivities' %}">Activities</a></li>
{% endblock %}

{% block content %}
  {% for i in logs %}
  <div class="modal fade" id="myModal{{i.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Delete Log</h4>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete this log.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-danger" onClick="location.href='{% url 'delLog' i.id %}';">
              Delete
              <span class="glyphicon glyphicon-remove"></button>
        </button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  {% endfor %}
  <div class="row">
      <div class="col-md-10">
          <ul class="list-inline">
              <li>
              <h1>All Logs</h1> 
              </li>
              {% if totalTime %}
              <li>
              <h4><span class="label label-primary">Total time {% widthratio totalTime 60 1 %} min</span></h4>
              </li>
              {% else %}
              <li>
              <h4><span class="label label-primary">Total time 0 min</span></h4>
              </li>
              {% endif %}
            </ul>
    {% regroup logs by date as date_list %}
    {% for i in date_list %}
    <h1>{{ i.grouper }}</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Notes</th>
                <th>Time</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for item in i.list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.notes }}</td>
                <td>{% widthratio item.time 60 1 %} min</td>
                <td>{{ item.date }}</td>
                <td><a data-toggle="modal" href="#myModal{{item.id}}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></button></a>
                        <a href="{% url 'editLog' item.id %}"><button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></button></a></td>
            </tr>
                        {% endfor %}
        </tbody>
    </table>
    {% endfor %}
</div>
</div>
{% endblock %}

timeTracker/timeLogger/templates/base.html
{% load staticfiles %}
<html lang="en">
<head>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
<link href="{% static "css/datepicker.css" %}" rel="stylesheet">
<script src="{% static "js/bootstrap.js" %}"></script>
<script src="{% static "js/bootstrap-datepicker.js" %}"></script>
<script src="{% static "js/runner.js" %}"></script>
<script type="text/javascript">
    {% block js %}
    {% endblock %}
</script>
</head>
</body>
<div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Time Tracker</a>
        </div>
        <div class="collapse navbar-collapse">
           <ul class="nav navbar-nav">
                {% block nav %}
                {% endblock %}
          </ul>
           <ul class="nav navbar-nav navbar-right">
               {% block nav.right %}
               {% endblock %}
               {% if user.is_authenticated %}
               <li>     <button type="button" class="btn btn-default navbar-btn dropdown-toggle" data-toggle="dropdown">
                    {{ user.username }} <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="/accounts/{{user.username}}">Profile Settings</a></li>
                    <li><a href="/accounts/signout">Sign out</a></li>
                </ul>
                </li>
                {% else %}
                {% if user.is_authenticated %}
                {% else %}
                <li><a href={% url 'userena_signin' %}>Sign in</a></li>
                <li><a href={% url 'userena_signup' %}>Sign up</a></li>
                {% endif %}
                {% endif %}
           </ul>
           
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
        {% block content %}{% endblock %}
      </div>

    </div><!-- /.container -->
  </body>
</html>

timeTracker/timeLogger/templates/detailedLog.html
{% extends "base.html" %}
{% block nav %}
    <li><a href="{% url 'logs' %}">Activity Log</a></li>
    <li><a href="{% url 'showActivities' %}">Activities</a></li>
{% endblock %}

{% block content %}
  {% for i in logs %}
  <div class="modal fade" id="myModal{{i.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Delete Log</h4>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete this log.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-danger" onClick="location.href='{% url 'delLog' i.id %}';">
              Delete
              <span class="glyphicon glyphicon-remove"></button>
        </button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  {% endfor %}
  <div class="row">
      <div class="col-md-10">
          <ul class="list-inline">
              <li>
              <h1>Last 7 Days</h1> 
              </li>
              {% if totalTime %}
              <li>
              <h4><span class="label label-primary">Total time {% widthratio totalTime 60 1 %} min</span></h4>
              </li>
              {% else %}
              <li>
              <h4><span class="label label-primary">Total time 0 min</span></h4>
              </li>
              {% endif %}
            </ul>
    {% regroup logs by date as date_list %}
    {% for i in date_list %}
    <h1>{{ i.grouper }}</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Notes</th>
                <th>Time</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for item in i.list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.notes }}</td>
                <td>{% widthratio item.time 60 1 %} min</td>
                <td>{{ item.date }}</td>
                <td><a data-toggle="modal" href="#myModal{{item.id}}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></button></a>
                        <a href="{% url 'editLog' item.id %}"><button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></button></a></td>
            </tr>
                        {% endfor %}
        </tbody>
    </table>
    {% endfor %}
</div>
</div>
{% endblock %}

timeTracker/timeLogger/templates/form.html
{% extends 'base.html' %}
{% block nav %}
    <li><a href="{% url 'logs' %}">Activity Log</a></li>
    <li><a href="{% url 'showActivities' %}">Activities</a></li>
{% endblock %}
{% block content %}
<h1>{{logs.name}}</h1>
            <form action="" method="post">{% csrf_token %}
                <table class="table table-condensed">
                    {% for field in form %}
                <tr>
                    <th>
                        {{ field.label_tag }}
                    </th>
                    <td>
                        {% if 'date' in field.label_tag %} 
                        <div class="input-group">
                            {{ field }} 
                            <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                            {{ field.errors }}
                        </div>
                        {% elif 'time' in field.label_tag %}
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button id="startButton" class="btn btn-success" type="button">Start</button>
                                <button id="stopButton" class="btn btn-danger" type="button">Stop</button>
                            </span>
                            </span>
                            {{ field }} 
                            {{ field.errors }}
                        </div>
                        {% else %}
                            {{ field }} 
                            {{ field.errors }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </form>
    {% csrf_token %}
    <button type="button" onClick="location.href='{% url 'logs' %}';" class="btn btn-default">Cancel</button>
    <button type="button" onClick="document.forms[0].submit();return false;" class="btn btn-primary">Save Changes</button>
</form>
{% endblock %}

{% block js %}
window.onbeforeunload = function(e) {
  return 'Dialog text here.';
};

$(document).ready(function(){ 
$("input").addClass("form-control");
$("#id_date").addClass("datepicker");
$("#id_date").attr('value', '{% now 'Y-m-d' %}');
$("#id_date").attr('data-date', '{% now 'Y-m-d' %}');
$("#id_date").attr('data-date-format', 'yyyy-mm-dd');
$('.datepicker').datepicker({
    format: 'yyyy-mm-dd',
    autoclose: 'true',
    todayHighlight: 'true',
    });
$('#id_time').runner({
    milliseconds: false,
    startAt: {{ form.time.value }} * 1000,
    format: function millisecondsToString(milliseconds) {
                                        var oneHour = 3600000;
                                        var oneMinute = 60000;
                                        var oneSecond = 1000;
                                        var seconds = 0;
                                        var minutes = 0;
                                        var hours = 0;
                                        var result;
 
                                        if (milliseconds >= oneHour) {
                                            hours = Math.floor(milliseconds / oneHour);
                                        }
 
                                        milliseconds = hours > 0 ? (milliseconds - hours * oneHour) : milliseconds;
 
                                        if (milliseconds >= oneMinute) {
                                            minutes = Math.floor(milliseconds / oneMinute);
                                        }
 
                                        milliseconds = minutes > 0 ? (milliseconds - minutes * oneMinute) : milliseconds;
 
                                        if (milliseconds >= oneSecond) {
                                            seconds = Math.floor(milliseconds / oneSecond);
                                        }
 
                                        milliseconds = seconds > 0 ? (milliseconds - seconds * oneSecond) : milliseconds;
 
                                        if (hours > 0) {
                                            result = (hours > 9 ? hours : "0" + hours) + ":";
                                        } else {
                                            result = "00:";
                                        }
 
                                        if (minutes > 0) {
                                            result += (minutes > 9 ? minutes : "0" + minutes) + ":";
                                        } else {
                                            result += "00:";
                                        }
 
                                        if (seconds > 0) {
                                            result += (seconds > 9 ? seconds : "0" + seconds);
                                        } else {
                                            result += "00";
                                        }
                                       
                                        return result;
                                    }  
                                   
});
$('#startButton').click(function() {
    $('#id_time').runner('start');
});
$('#stopButton').click(function() {
    $('#id_time').runner('stop');
});

});
{% endblock %}

timeTracker/timeLogger/templates/home.html
{% extends 'base.html' %}
{% block nav %}
{% if user.is_authenticated %}
    <li><a href="{% url 'logs' %}">Activity Log</a></li>
    <li><a href="{% url 'showActivities' %}">Activities</a></li>
{% endif %}
{% endblock %}
{% block content %}
<div class="jumbotron">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
      </div>
  </div>
{% endblock %}

timeTracker/timeLogger/templates/log.html
{% extends "base.html" %}
{% debug %}
{% block nav %}
<li class="active"><a href="{% url 'logs' %}">Activity Log</a></li>
<li><a href="{% url 'showActivities' %}">Activities</a></li>
{% endblock %}

{% block content %}
{% for i in logs %}
<div class="modal fade" id="myModal{{i.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Delete Log</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this log.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" onClick="location.href='{% url 'delLog' i.id %}';">
                    Delete
                    <span class="glyphicon glyphicon-remove"></button>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endfor %}
<div class="row">
    <div class="col-xs-12 col-md-12">
        <ul class="list-inline">
            <li>
            <h1>Today's Logs</h1> 
            </li>
            <li>
            {% if totalTime %}
            <h4><span class="label label-primary">Total time today {% widthratio totalTime 60 1 %} min</span></h4>
            {% else %}
            <h4><span class="label label-primary">Total time today 0 min</span></h4>
            {% endif %}
            </li>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-md-9">
            {% if logs %}
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Notes</th>
                        <th>Time</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in logs %}
                    <tr>
                        <td>{{ i.name }}</td>
                        <td>{{ i.notes }}</td>
                        <td>{% widthratio i.time 60 1 %} min</td>
                        <td><a data-toggle="modal" href="#myModal{{i.id}}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></button></a>
                                <a href="{% url 'editLog' i.id %}"><button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></button></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
            <div class="col-xs-12 col-md-9">
                 <div class="alert alert-info"><p>Look and pick a activity to start to get started.</p></div>
            </div>
            {% endif %}
                <div class="col-xs-12 col-md-3">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Activities </th>
                                <th>Create</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in activities %}
                            <tr>
                                <td>{{ i.name }}</td>
                                <td><a class="btn btn-success" href="{% url 'addLog' i.id %}">Start</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <ul class="list-inline">
                    <li>
                    <a href="{% url 'logsLast7' %}" class="btn btn-primary">Last 7 Days</a>
                    <a href="{% url 'showAllLogs' %}" class="btn btn-primary">All</a>
                    </li>
                </ul>
            </div>
            {% endblock %}
            {% block js %}
            $(document).ready(function(){ 
            $("input").addClass("form-control");
            $("textarea").addClass("form-control");
            $("select").addClass("form-control");
            $("#id_date").addClass("datepicker");
            $("#id_date").attr('value', '{% now 'Y-m-d' %}');
            $("#id_date").attr('data-date', '{% now 'Y-m-d' %}');
            $("#id_date").attr('data-date-format', 'yyyy-mm-dd');
            $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: 'true',
            todayHighlight: 'true',
            endDate: '{% now 'Y-m-d' %}',
            });
            $('#id_time').runner({
            milliseconds: false,
            {% if form.time.value %}
            startAt: {{ form.time.value}} * 1000,
            {% endif %}
            format: function millisecondsToString(milliseconds) {
            var oneHour = 3600000;
            var oneMinute = 60000;
            var oneSecond = 1000;
            var seconds = 0;
            var minutes = 0;
            var hours = 0;
            var result;

            if (milliseconds >= oneHour) {
            hours = Math.floor(milliseconds / oneHour);
            }

            milliseconds = hours > 0 ? (milliseconds - hours * oneHour) : milliseconds;

            if (milliseconds >= oneMinute) {
            minutes = Math.floor(milliseconds / oneMinute);
            }

            milliseconds = minutes > 0 ? (milliseconds - minutes * oneMinute) : milliseconds;

            if (milliseconds >= oneSecond) {
            seconds = Math.floor(milliseconds / oneSecond);
            }

            milliseconds = seconds > 0 ? (milliseconds - seconds * oneSecond) : milliseconds;

            if (hours > 0) {
            result = (hours > 9 ? hours : "0" + hours) + ":";
            } else {
            result = "00:";
            }

            if (minutes > 0) {
            result += (minutes > 9 ? minutes : "0" + minutes) + ":";
            } else {
            result += "00:";
            }

            if (seconds > 0) {
            result += (seconds > 9 ? seconds : "0" + seconds);
            } else {
            result += "00";
            }

            return result;
            }  

            });
            $('#startButton').click(function() {
            $('#id_time').runner('start');
            });
            $('#stopButton').click(function() {
            $('#id_time').runner('stop');
            });
            });
            {% endblock %}